### ISSUE TITLE
Server error when trying to download the dataset

### ISSUE THREAD

**Issue by CretuCalin** [ThanosM97/end-to-end-chess-recognition#1]
<img width="849" alt="image" src="https://github.com/ThanosM97/end-to-end-chess-recognition/assets/17611027/0dfcd569-4078-4e70-9099-da5913616cbc">

**Comment by tmasouris** [comment]
Hi @CretuCalin ,

This is a host-related issue, perhaps there is a scheduled maintenance. 

The dataset is hosted here:  [https://data.4tu.nl/datasets/99b5c721-280b-450b-b058-b2900b69a90f/2](https://data.4tu.nl/datasets/99b5c721-280b-450b-b058-b2900b69a90f/2)

Please try again later. Sorry for the inconvenience.
